/**
 * Created by sonyakhan on 2/17/16.
 */



var quotes = [
    "If opportunity doesn't knock, build a door.",
    "Try to be a rainbow in someone's cloud.",
    "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.",
    "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all ― in which case, you fail by default.",
    "Success usually comes to those who are too busy to be looking for it.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.",
    "Try not to become a person of success, but rather try to become a person of value.",
    "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "No one can make you feel inferior without your consent.",
    "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.",
    "Courage is resistance to fear, mastery of fear – not absence of fear.",
    "Only put off until tomorrow what you are willing to die having left undone.",
    "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.",
    "The successful warrior is the average man, with laserlike focus.",
    "Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential.",
    "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    "Think of what you have rather than of what you lack. Of the things you have, select the best and then reflect how eagerly you would have sought them if you did not have them.",
    "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.",
    "Keep your fears to yourself, but share your courage with others.",
    "Power isn't control at all-power is strength, and giving that strength to others. A leader isn't someone who forces others to make him stronger; a leader is someone willing to give his strength to others that they may have the strength to stand on their own.",
    "A leader ... is like a shepherd. He stays behind the flock, letting the most nimble go out ahead, whereupon the others follow, not realizing that all along they are being directed from behind.",
    "Don't tell people how to do things; tell them what to do and let them surprise you with their results.",
    "If you want to build a ship, don't drum up the men to gather wood, divide the work, and give orders. Instead, teach them to yearn for the vast and endless sea.",
    "Show me the man you honor and I will know what kind of man you are.",
    "A good plan violently executed now is better than a perfect plan executed next week.",
    "Feeling gratitude and not expressing it is like wrapping a present and not giving it.",
    "You wouldn't worry so much about what others think of you if you realized how seldom they do.",
    "Low self-confidence isn't a life sentence. Self-confidence can be learned, practiced, and mastered-just like any other skill. Once you master it, everything in your life will change for the better.",
    "The best revenge is massive success.",
    "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    "Life is 10% what happens to me and 90% of how I react to it.",
    "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "To handle yourself, use your head; to handle others, use your heart.",
    "Too many of us are not living our dreams because we are living our fears.",
    "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
    "The most common way people give up their power is by thinking they don’t have any.",
    "Don’t judge each day by the harvest you reap but by the seeds that you plant.",
    "Build your own dreams, or someone else will hire you to build theirs.",
    "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
    "You can’t use up creativity. The more you use, the more you have.",
    "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
    "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.",
    "Everything has beauty, but not everyone can see.",
    "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down “happy”. They told me I didn’t understand the assignment, and I told them they didn’t understand life.",
    "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "We can’t help everyone, but everyone can help someone.",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples.",
    "If you want to lift yourself up, lift up someone else."
];

var authors = [
    "— Milton Berle",
    "— Maya Angelou",
    "— Ralph Waldo Emerson",
    "— J. K. Rowling",
    "— Henry David Thoreau",
    "— Jim Rohn",
    "— Winston Churchill",
    "— Vaibhav Shah",
    "— Albert Einstein",
    "— Charles Darwin",
    "— Eleanor Roosevelt",
    "— Eleanor Roosevelt",
    "— Ray Goforth",
    "— Mark Twain",
    "— Pablo Picasso",
    "— Mark Twain",
    "— Bruce Lee",
    "— John Maxwell",
    "— Maya Angelou",
    "— Marcus Aurelius",
    "— William Arthur Ward",
    "— Robert Louis Stevenson",
    "— Beth Revis",
    "— Nelson Mandela",
    "— George S. Patton Jr.",
    "— Antoine de Saint-Exupery",
    "— Thomas John Carlisle",
    "— George Patton",
    "— William Arthur Ward",
    "— Eleanor Roosevelt",
    "— Barrie Davenport",
    "— Frank Sinatra",
    "— Vince Lombardi",
    "— Charles Swindoll",
    "— Oprah Winfrey",
    "— Jimmy Dean",
    "— Eleanor Roosevelt",
    "— Les Brown",
    "— Michael Jordan",
    "— Stephen Covey",
    "— Henry Ford",
    "— Alice Walker",
    "— Robert Louis Stevenson",
    "— Farrah Gray",
    "— Dalai Lama",
    "— Maya Angelou",
    "— Bob Dylan",
    "— Jamie Paolinetti",
    "— Helen Keller",
    "— Confucius",
    "— John Lennon",
    "— Plato",
    "— George Addair",
    " — Ronald Reagan",
    "— Mother Teresa",
    "— Booker T. Washington"
];

function generate() {
    var randomNum = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerHTML = quotes[randomNum];
    document.getElementById("author").innerHTML = authors[randomNum];
}

document.onload = generate();



